### ISSUE TITLE
The IBeaconManager is not bound to the service

### ISSUE THREAD

**Issue by Guti** [jamesfalkner/liferay-android-beacons#1]
I get this error message:

android.os.RemoteException: The IBeaconManager is not bound to the service.  Call iBeaconManager.bind(IBeaconConsumer consumer) and wait for a callback to onIBeaconServiceConnect()

**Comment by jamesfalkner** [comment]
@egenia not possible with my wrapper (it requires a proximityUuid) but I will try it tomorrow without a uuid and see if it's possible.

**Comment by kangkingkong** [comment]
Hi James,

I got the same problem when i tried to modify the example codes or if i call it in another file beside app.js... the reason why i want to put it in another file is because Im using the app.js as the page transition manager which will call other JS files.

Any suggestion on this please ?

**Comment by andersjj** [comment]
Just tried to download and use the module in the current release of Appcelerator Studio 4.3.1 with SDK 5.0.  Any known issues that would prevent it from running?  I tried downloading the Classic Titanium Sample and couldn't get it to work.  Kept getting the same "not bound to service" message that others have experienced.  Not sure if I'm seeing the issue because of SDK 5.0 or some other config issue that might be stopping me.

**Comment by andersjj** [comment]
Never mind, got it working, the problem was between the chair and the keyboard.

**Comment by torlanco** [comment]
andersjj, Im having that same problem right now, could you share how you resolved it?

**Comment by torlanco** [comment]
I am getting the following error in Titanium SDK 5.0.2.GA

```[ERROR] :  LiferayBeaconsModule: (KrollRuntimeThread) [1,272802] Cannot start monitoring region {major=53376, identifier=iBeacon1, minor=40477, uuid=B9407F30-F5F8-466E-AFF9-25556B57FE6D}
[ERROR] :  LiferayBeaconsModule: android.os.RemoteException: The IBeaconManager is not bound to the service.  Call iBeaconManager.bind(IBeaconConsumer consumer) and wait for a callback to onIBeaconServiceConnect()
[ERROR] :  LiferayBeaconsModule: 	at com.radiusnetworks.ibeacon.IBeaconManager.startMonitoringBeaconsInRegion(IBeaconManager.java:440)
[ERROR] :  LiferayBeaconsModule: 	at com.liferay.beacons.LiferayBeaconsModule.startMonitoringForRegion(LiferayBeaconsModule.java:196)
[ERROR] :  LiferayBeaconsModule: 	at org.appcelerator.kroll.runtime.v8.V8Object.nativeCallProperty(Native Method)
[ERROR] :  LiferayBeaconsModule: 	at org.appcelerator.kroll.runtime.v8.V8Object.callProperty(V8Object.java:73)
[ERROR] :  LiferayBeaconsModule: 	at org.appcelerator.kroll.KrollProxy.handleMessage(KrollProxy.java:1145)
[ERROR] :  LiferayBeaconsModule: 	at android.os.Handler.dispatchMessage(Handler.java:98)
[ERROR] :  LiferayBeaconsModule: 	at android.os.Looper.loop(Looper.java:155)
[ERROR] :  LiferayBeaconsModule: 	at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:112)
[ERROR] :  LiferayBeaconsModule: (KrollRuntimeThread) [0,272808] Cannot start monitoring region {major=6517, identifier=iBeacon2, minor=22517, uuid=8492E75F-4FD6-469D-B132-043FE94921D8}
[ERROR] :  LiferayBeaconsModule: android.os.RemoteException: The IBeaconManager is not bound to the service.  Call iBeaconManager.bind(IBeaconConsumer consumer) and wait for a callback to onIBeaconServiceConnect()
[ERROR] :  LiferayBeaconsModule: 	at com.radiusnetworks.ibeacon.IBeaconManager.startMonitoringBeaconsInRegion(IBeaconManager.java:440)
[ERROR] :  LiferayBeaconsModule: 	at com.liferay.beacons.LiferayBeaconsModule.startMonitoringForRegion(LiferayBeaconsModule.java:196)
[ERROR] :  LiferayBeaconsModule: 	at org.appcelerator.kroll.runtime.v8.V8Object.nativeCallProperty(Native Method)
[ERROR] :  LiferayBeaconsModule: 	at org.appcelerator.kroll.runtime.v8.V8Object.callProperty(V8Object.java:73)
[ERROR] :  LiferayBeaconsModule: 	at org.appcelerator.kroll.KrollProxy.handleMessage(KrollProxy.java:1145)
[ERROR] :  LiferayBeaconsModule: 	at android.os.Handler.dispatchMessage(Handler.java:98)
[ERROR] :  LiferayBeaconsModule: 	at android.os.Looper.loop(Looper.java:155)
[ERROR] :  LiferayBeaconsModule: 	at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:112)
[ERROR] :  LiferayBeaconsModule: (KrollRuntimeThread) [1,272813] Cannot start monitoring region {major=6518, identifier=iBeacon3, minor=22518, uuid=8492E75F-4FD6-469D-B132-043FE94921D8}
[ERROR] :  LiferayBeaconsModule: android.os.RemoteException: The IBeaconManager is not bound to the service.  Call iBeaconManager.bind(IBeaconConsumer consumer) and wait for a callback to onIBeaconServiceConnect()
[ERROR] :  LiferayBeaconsModule: 	at com.radiusnetworks.ibeacon.IBeaconManager.startMonitoringBeaconsInRegion(IBeaconManager.java:440)
[ERROR] :  LiferayBeaconsModule: 	at com.liferay.beacons.LiferayBeaconsModule.startMonitoringForRegion(LiferayBeaconsModule.java:196)
[ERROR] :  LiferayBeaconsModule: 	at org.appcelerator.kroll.runtime.v8.V8Object.nativeCallProperty(Native Method)
[ERROR] :  LiferayBeaconsModule: 	at org.appcelerator.kroll.runtime.v8.V8Object.callProperty(V8Object.java:73)
[ERROR] :  LiferayBeaconsModule: 	at org.appcelerator.kroll.KrollProxy.handleMessage(KrollProxy.java:1145)
[ERROR] :  LiferayBeaconsModule: 	at android.os.Handler.dispatchMessage(Handler.java:98)
[ERROR] :  LiferayBeaconsModule: 	at android.os.Looper.loop(Looper.java:155)
[ERROR] :  LiferayBeaconsModule: 	at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:112)
[ERROR] :  LiferayBeaconsModule: (KrollRuntimeThread) [1,272818] Cannot start monitoring region {major=6519, identifier=iBeacon4, minor=22519, uuid=8492E75F-4FD6-469D-B132-043FE94921D8}
[ERROR] :  LiferayBeaconsModule: android.os.RemoteException: The IBeaconManager is not bound to the service.  Call iBeaconManager.bind(IBeaconConsumer consumer) and wait for a callback to onIBeaconServiceConnect()
[ERROR] :  LiferayBeaconsModule: 	at com.radiusnetworks.ibeacon.IBeaconManager.startMonitoringBeaconsInRegion(IBeaconManager.java:440)
[ERROR] :  LiferayBeaconsModule: 	at com.liferay.beacons.LiferayBeaconsModule.startMonitoringForRegion(LiferayBeaconsModule.java:196)
[ERROR] :  LiferayBeaconsModule: 	at org.appcelerator.kroll.runtime.v8.V8Object.nativeCallProperty(Native Method)
[ERROR] :  LiferayBeaconsModule: 	at org.appcelerator.kroll.runtime.v8.V8Object.callProperty(V8Object.java:73)
[ERROR] :  LiferayBeaconsModule: 	at org.appcelerator.kroll.KrollProxy.handleMessage(KrollProxy.java:1145)
[ERROR] :  LiferayBeaconsModule: 	at android.os.Handler.dispatchMessage(Handler.java:98)
[ERROR] :  LiferayBeaconsModule: 	at android.os.Looper.loop(Looper.java:155)
[ERROR] :  LiferayBeaconsModule: 	at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:112)```

My tiapp.xml looks like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<ti:app xmlns:ti="http://ti.appcelerator.org">
    <id>com.mlstudio.prego</id>
    <name>Chef Prego</name>
    <version>1.0</version>
    <publisher>torlanco</publisher>
    <url>https://www.facebook.com/PregoPR</url>
    <description>undefined</description>
    <copyright>2015 by torlanco</copyright>
    <icon>defaulticon.png</icon>
    <fullscreen>false</fullscreen>
    <navbar-hidden>false</navbar-hidden>
    <analytics>true</analytics>
    <guid>4042b5de-412f-44ac-9000-132382f49197</guid>
    <property name="ti.ui.defaultunit" type="string">dp</property>
    <android xmlns:android="http://schemas.android.com/apk/res/android">
        <manifest android:versionCode="2" android:versionName="0.6" package="com.mlstudio.prego">
            <uses-sdk android:minSdkVersion="14" android:targetSdkVersion="21"/>
			<uses-permission android:name="android.permission.BLUETOOTH"/>
			<uses-permission android:name="android.permission.BLUETOOTH_ADMIN"/>
			
            <application android:theme="@style/Theme.Titanium">
				<service android:enabled="true"
				  android:exported="true"
				  android:isolatedProcess="false"
				  android:label="iBeacon"
				  android:name="com.radiusnetworks.ibeacon.service.IBeaconService">
				</service>
				<service android:enabled="true" android:name="com.radiusnetworks.ibeacon.IBeaconIntentProcessor">
				  <meta-data android:name="background" android:value="true" />
				  <intent-filter android:priority="1" >
					<action android:name="com.mlstudio.prego.DID_RANGING"/>
					<action android:name="com.mlstudio.prego.DID_MONITORING"/>
				  </intent-filter>
				</service>
              <activity
                  android:configChanges="keyboard|orientation|screenSize"
                  android:label="@string/app_name"
                  android:screenOrientation="portrait"
                  android:theme="@style/Theme.Titanium" android:windowSoftInputMode="stateAlwaysVisible">
                  <intent-filter>
                      <action android:name="android.intent.action.MAIN"/>
                      <category android:name="android.intent.category.LAUNCHER"/>
                  </intent-filter>
              </activity>
              <activity
                  android:configChanges="keyboard|orientation|screenSize"
                  android:name="org.appcelerator.titanium.TiActivity" android:screenOrientation="portrait"/>
              <activity
                  android:configChanges="keyboard|orientation|screenSize"
                  android:name="org.appcelerator.titanium.TiTranslucentActivity"
                  android:screenOrientation="portrait" android:theme="@style/Theme.AppCompat.Translucent"/>
              <activity android:configChanges="screenSize"
                  android:name="ti.modules.titanium.ui.android.TiPreferencesActivity" android:screenOrientation="portrait"/>
              <activity
                  android:configChanges="keyboard|orientation|screenSize"
                  android:name="ti.modules.titanium.media.TiCameraActivity"
                  android:screenOrientation="portrait" android:theme="@style/Theme.AppCompat.Translucent.NoTitleBar.Fullscreen"/>
              <service android:exported="false" android:name="com.appcelerator.analytics.APSAnalyticsService"/>
              <activity android:label="@string/app_name" android:name="com.facebook.LoginActivity" android:theme="@android:style/Theme.Translucent.NoTitleBar"/>
              <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id"/>
            </application>

        </manifest>
    </android>
    <mobileweb>
        <precache/>
        <splash>
            <enabled>true</enabled>
            <inline-css-images>true</inline-css-images>
        </splash>
        <theme>default</theme>
    </mobileweb>
    <modules>
        <module platform="android" version="4.0.5">facebook</module>
        <module platform="android">ti.map</module>
        <module platform="android" version="0.3">com.liferay.beacons</module>
    </modules>
    <deployment-targets>
        <target device="android">true</target>
        <target device="ipad">false</target>
        <target device="iphone">false</target>
        <target device="mobileweb">false</target>
        <target device="windows">false</target>
    </deployment-targets>
    <sdk-version>5.0.2.GA</sdk-version>
    <plugins>
        <plugin version="1.0">ti.alloy</plugin>
    </plugins>
    <property name="appc-app-id" type="string">5612df0bf96eaa1a65d3949e</property>
</ti:app>
```

**Comment by andersjj** [comment]
I actually had a mistake in my tiapp.xml.  I accidentally doubled up my <android tag in the xml.  Once I cleaned up that it worked like a champ.

**Comment by torlanco** [comment]
@andersjj maybe you could help me out with my most recent post, Im having the "not bound to service" in sdk 5, can't find any way to fix it. Could you share your code if you have it working? at least the tiapp.xml

**Comment by andersjj** [comment]
Here's my tiapp.xml - just remember to add your package id where appropriate and give your app a few seconds to get the BLE up and running. I have a timeout of 5 seconds before I try to start any beacon operations 







< android xmlns:android = "http://schemas.android.com/apk/res/android"> 

< manifest package = "package name"> 

< uses - sdk android:minSdkVersion = "14" android:targetSdkVersion = "22"/> 

< uses - permission android:name = "android.permission.BLUETOOTH"/> 

< uses - permission android:name = "android.permission.BLUETOOTH_ADMIN"/> 

< application > 

< service android:enabled = "true" android:exported = "true" 

android:isolatedProcess = "false" 

android:label = "iBeacon" android:name = "com.radiusnetworks.ibeacon.service.IBeaconService"/> 

< service android:enabled = "true" android:name = "com.radiusnetworks.ibeacon.IBeaconIntentProcessor"> 

< meta - data android:name = "background" android:value = "true"/> 

< intent - filter android:priority = "1"> 

< action android:name = " package name" .DID_RANGING"/> 

< action android:name = " package name" .DID_MONITORING"/> 

</ intent - filter > 

</ service > 

</ application > 

</ manifest > 

</ android > 

----- Original Message -----

**Comment by torlanco** [comment]
@andersjj my tiapp.xml is just like yours and it still doesn't work, this is frustrating but Im determined! :) 

maybe im writing my app id wrong? should it be encapsulated in some way? Right now I have this:

```<action android:name="com.mlstudio.prego.DID_RANGING"/>
                        <action android:name="com.mlstudio.prego.DID_MONITORING"/>```

**Comment by andersjj** [comment]
app id looks good. Just make sure to have a delay before you try to start ranging or monitoring for regions. I use a setimeout of 5 secs to give it a chance to boot up. 

Also, I'm building on 5.0.0 GA SDK, I haven't tried anything higher than that. Maybe give it a go on 5.0.0 GA and see if that works. Probably won't make a diff, but worth a try. 



----- Original Message -----

**Comment by torlanco** [comment]
I built using 5.0.0.GA and the problem persists.

This is how im calling the startMonitoringForRegion:

```
var TiBeacons = require('com.liferay.beacons');
var parse = require('parse');

var setupAndStartMonitors = function() {

  setTimeout(function(){

  // get beacons from parse
  parse.getBeacons(null, function(response){
    var data = JSON.parse(response.responseText);

    if(data.results.length > 0){

      // go through each beacon in the result set
      for( var i = 0; i < data.results.length; i++){
        // monitor beacon regions
        TiBeacons.startMonitoringForRegion({
          uuid : data.results[i].uuid,
          identifier : data.results[i].identifier,
          major: data.results[i].maj,
          minor: data.results[i].min
        });
      }

    }
  });
  }, 20000);

};
exports.setupAndStartMonitors = setupAndStartMonitors;
```

I call setupAndStartMonitors from another file. As you guys can see, Im giving it 20 seconds to load; I have tried other values.

**Comment by achimhoth** [comment]
Same here. SOMEtimes the service will already be bound and it works fine but most of the time I get the "The IBeaconManager is not bound to the service." error.

**Comment by jamesfalkner** [comment]
Give the 0.4 version a go - @nitrag [contributed a new API](https://github.com/jamesfalkner/liferay-android-beacons/pull/13) for checking when it's ready. See the example at

**Comment by achimhoth** [comment]
Yes, checking for ready state does help! Thanks alot

**Comment by RBAtkins0n** [comment]
@jamesfalkner this issue can be marked resolved.
