### ISSUE TITLE
Does this module is a multiple method of recognizing ?

### ISSUE THREAD

**Issue by elmar28** [jamesfalkner/liferay-android-beacons#10]
How can I recognize the two beacons , or this module is compatible ?

**Comment by jamesfalkner** [comment]
What do you mean "recognize" ? You can turn on ranging for a region, and you will get callbacks for all beacons within that region.

You can also monitor for multiple regions at the same time using different uuid/major/minor combinations.

**Comment by elmar28** [comment]
Do startMonitoringForRegion you need to call to the specified things of major if the uuid is acquired by changing the major / minor in the same ?

You are looking at the response , but if major is not specified other than the first one that is acquired , you can not get a response .

Or UUID can be acquired output to locate the same on the automatic ?

**Comment by elmar28** [comment]
It was my mistake .
major / minor had been able to get .
Is there a way to take the number of beacon that is monitoring ?

**Comment by jamesfalkner** [comment]
Each beacon only transmits 3 identifiers: UUID, major, and minor. beacons themselves cannot monitor other beacons. Only bluetooth receivers (e.g. smartphones) can perform the monitoring.

During ranging, your callback will get called once for each beacon that it "sees". Each beacon will have a `uuid`, `major`, and `minor` value (and an `identifier` string which tells you in which region the beacon is. There are a few other items passed, but not important for identification of the beacon.

Some other libraries might call your callback once, and pass a complete array of "seen" beacons. But this one does not do that.

Hope this helps!

**Comment by elmar28** [comment]
All right.
By creating a monitoring process with self-made , the number of beacon to determine .

Thank you

**Comment by jamesfalkner** [comment]
So you want to know how many beacons are "seen" during ranging? 

Not currently possible with this library but I can add this in if this is what you're looking for.

**Comment by elmar28** [comment]
Is really !

I want to determine the beacon in the nearest in the beacon you are monitoring .

{"type": "beaconProximity",
"source": {
"bubbleParent": true,
"apiName": "Ti.Module",
"invocationAPIs": [],
"_events": {
"beaconProximity": {},
"enteredRegion": {},
"exitedRegion": {}
}
} ,
"proximity": "far",
"minor": 5,
"power": - 59,
"rssi": - 90,
"uuid": "000000-0000-0000-0000-000000000000",
"accuracy": 23.44427636162588,
"identifier": "FOO",
"major": 5,
"bubbles": false,
"cancelBubble": false
}

The current response .

In this response
Now , of you are monitoring , and what number of beacon of the
It is want is determined to 'key'

And get to do this ,
I can hold as an array the response of the acquired beacon app

**Comment by jamesfalkner** [comment]
Ok I will add another event which will give you all beacons in an array. But you will still need to calculate the distance to each beacon because this is not something that the OS calculates.

**Comment by elmar28** [comment]
Thanks you.

state you do not know some are monitoring the reaction was not when the beacon is okay if it is eliminated.

Calculation processing of distance I can make on your own

**Comment by jamesfalkner** [comment]
I'd rather leave in the `unknown` proximities, and let the mobile OS determine when to drop it from the list :) So if you want to eliminate them, just strip them out if they are `unknown`. I'll publish an update in about an hour after my android tablet charges enough to test this :)

**Comment by elmar28** [comment]
So I 'm get to correspond immediately !

Thank you very much !

**Comment by jamesfalkner** [comment]
Ok I've added this and re-generated the binary release - 0.3 in the `dist` directory. Let me know if it works for you! You'll need to listen for the `beaconRanges` event (and not the `beaconProximity` event).

**Comment by elmar28** [comment]
Thanks you.
I 'll try tomorrow morning .
When you work, you will be reported .

**Comment by elmar28** [comment]
Tried .
I was able to confirm the operation .
Thank you very much .

**Comment by jamesfalkner** [comment]
Hurray! Thanks for testing so quickly..
