### ISSUE TITLE
Callback for service ready

### ISSUE THREAD

**Issue by nitrag** [jamesfalkner/liferay-android-beacons#12]
First off, this is a sweet module! Thanks so much for putting it together.

Right now, I have a setTimeout to wait 8 seconds before setting up the event listeners. I need to start advertising ASAP so I can't rely on a button click. I'm not sure if this is long enough and I certainly would like to shorten it. Is there anyway you can add a "onReady" eventListener when the module is ready? This way there is no guesswork on when it is ok to go ahead and setup the event listeners.

Thanks!

**Comment by nitrag** [comment]
Couldn't get a callback setup because it seems that onIBeaconServiceConnect fires twice.

My Pull Request:
https://github.com/jamesfalkner/liferay-android-beacons/pull/13

**Comment by jamesfalkner** [comment]
Committed (along with new binary). Thanks!
