### ISSUE TITLE
Uncaught Error: Requested module not found: com.liferay.beacons

### ISSUE THREAD

**Issue by morefun0302** [jamesfalkner/liferay-android-beacons#7]
I have downloaded your source and successfully build using 3.4.1.GA, I just changed the build.xml, 
when I use it in code using:

var TiBeacons = require('com.liferay.beacons');

I got the following error
Uncaught Error: Requested module not found: com.liferay.beacons

no matter I install the module in Titanium SDK or in my own app project

**Comment by jamesfalkner** [comment]
Did you add the module to your `tiapp.xml`file? 
```
<modules>
  <module platform="android">com.liferay.beacons</module>
</modules>
```

**Comment by morefun0302** [comment]
Yes
於 2015年1月19日 下午10:48，"James Falkner" <notifications@github.com> 寫道：

**Comment by jamesfalkner** [comment]
can you send me a zip file containing your project, and the output from `adb logcat` ?

**Comment by RBAtkins0n** [comment]
Old thread with no reply, @jamesfalkner this issue can be marked resolved.
