### ISSUE TITLE
Cannot Scan Beacons in background Service when the App is exited

### ISSUE THREAD

**Issue by morefun0302** [jamesfalkner/liferay-android-beacons#8]
I have setting up the App to start a background service, Beacons can still be scanned when the home button of the phone is pressed and the App is in background. But Beacons cannot be scanned when the App is exited.

I have checked that the Service of the App is still running.

Is it possible the scan Beacons even when the App is exited?

**Comment by jamesfalkner** [comment]
Not possible with this wrapper, as it uses an older Radius networks library - one of these days I'll find time to upgrade to using the [latest AltBeacon library](http://altbeacon.github.io/android-beacon-library/documentation.html) which I think does [support this](http://altbeacon.github.io/android-beacon-library/resume-after-terminate.html).
